import type { Metadata } from 'next'
import { Raleway } from 'next/font/google'
import './globals.css'
import { ClerkProvider, SignIn} from '@clerk/nextjs'
import { SignedIn } from '@clerk/nextjs/app-beta';
import { SignedOut } from '@clerk/nextjs/app-beta/client';
import Navbar from '@/components/Navbar';

const inter = Raleway({ subsets: ['latin'] })

export const metadata: Metadata = {
  title: 'Rental App',
  description: 'Generated by Maxiimus',
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <ClerkProvider>
    <html lang="en">
      <body className={inter.className}>
        <SignedIn>
          <Navbar/>
          {children}
        </SignedIn>
        <SignedOut>
          <SignIn/>
        </SignedOut>
      </body>
    </html>
    </ClerkProvider>
  )
}
